### ISSUE TITLE
Cannot read properties of undefined (currentOperand)

### ISSUE THREAD

**Issue by NathanSteinway** [NathanSteinway/React_Calc_App#3]
App.js:127 Uncaught TypeError: Cannot read properties of undefined (reading 'currentOperand')
    at App (App.js:127:1)
    at renderWithHooks (react-dom.development.js:16305:1)
    at updateFunctionComponent (react-dom.development.js:19588:1)
    at beginWork (react-dom.development.js:21601:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:1)
    at invokeGuardedCallback (react-dom.development.js:4277:1)
    at beginWork$1 (react-dom.development.js:27451:1)
    at performUnitOfWork (react-dom.development.js:26557:1)
    at workLoopSync (react-dom.development.js:26466:1)

**Comment by NathanSteinway** [comment]
Behavior: Upon clicking an operation button the application breaks.
